InfyOmLabs/infy-tracker

app/Http/Controllers/UserController.php
When create user with deactivate status then user will not receive confirmation mail but when we update that user with activate status then we need to send confirmation mail.
=> send activated email support user update

app/Http/Middleware/ValidateUserMiddleware.php, resources/assets/js/custom.js, resources/views/layouts/app.blade.php
If user is not authenticated than he/she will redirect to login page.
=> redirect user to login page if not authenticated

app/Http/Controllers/UserController.php, app/Repositories/UserRepository.php, resources/assets/js/users/user.js, resources/assets/style/sass/style.scss, resources/views/users/table.blade.php, routes/web.php
Send verification mail if user has not verified his/her email from users tab
=> Send verification mail if user has not verified his/her email

app/Http/Controllers/UserController.php, app/Http/Requests/UpdateUserProfileRequest.php, resources/assets/js/profile/profile.js, resources/views/layouts/app.blade.php, resources/views/users/index.blade.php, routes/web.php, webpack.mix.js
What change done?
- fixed issue password store as a plain text
- removed profile script from app blade and added in webmix
- fixed unassigned projects  while update profile
- fixed automatically deactivate account while update profile
=> feat(users): fixed update profile issues

resources/assets/js/task/task.js
When user create new task then assign select box is not rest.
=> fix(task): assign to not clear into new task after one task creation

app/Http/Controllers/UserController.php, app/Repositories/UserRepository.php, resources/assets/js/users/user.js, resources/views/users/table.blade.php, routes/web.php
What change done?
* active column added into users table
* user can active and deactive any user from table (toggle implemented)
UI Draft
=> feat(users): active column added into users

resources/assets/js/task/task.js
**Task**
- User does not able to select current date while adding new task
=> fix(task): User do not able to select current date while adding new task

app/Models/Task.php, app/Repositories/TaskRepository.php, database/migrations/2019_06_22_050515_add_priority_column_to_tasks_table.php, resources/assets/js/task/task.js, resources/assets/js/task/task_detail.js, resources/assets/style/sass/style.scss, resources/views/tasks/edit_modal.blade.php, resources/views/tasks/modal.blade.php, resources/views/tasks/show.blade.php, resources/views/tasks/task_edit_modal.blade.php
* priority support added to task
=> feat(task): priority column added to task

resources/assets/js/time_tracker/time_tracker.js
activity load again and again while project change in time tracker
=> fix: activity load again and again while project change in time tracker

resources/assets/js/projects/project.js, resources/views/projects/table.blade.php
What change made?
* Prefix column added in to project colmun
=> feat: prefix column added into project table

resources/assets/js/task/task_detail.js
#TIMETRACKE-106 Unable to set due date if it is passed dates
=> fix(task): #TIMETRACKE-106 Unable to set due date if it is passed dates

app/Http/Controllers/UserController.php, app/Repositories/ProjectRepository.php, app/Repositories/UserRepository.php
assignee and Project dropdown list should be assending order
=> fix: assignee and Project dropdown list should be assending order

resources/assets/js/task/task.js
Change eye icon to clock icon into tasks screen and also changed background color of button.
=> fix:  Change eye icon to clock icon into tasks screen

resources/views/tasks/edit_modal.blade.php, resources/views/tasks/modal.blade.php
Update modals of  New/Edit Task UI
=> fix(task): update modals of task screen for add/edit

resources/views/auth/login.blade.php, resources/views/auth/passwords/email.blade.php, resources/views/auth/passwords/reset.blade.php, resources/views/auth/register.blade.php, resources/views/auth/set_password.blade.php
fixed http issue of jqeury in UI
=> fix: https thing of jquery in ui

app/Http/Controllers/Auth/RegisterController.php, app/Http/Controllers/Auth/ResetPasswordController.php, app/Http/Controllers/Auth/VerificationController.php, app/Http/Middleware/RedirectIfAuthenticated.php, resources/views/layouts/menu.blade.php, routes/web.php
=> fix(hot fix): remove dashboard

routes/web.php
Added fall back route for wrong routes
=> feat(route): added fallback route for wrong route

resources/assets/js/task/task.js, resources/assets/style/sass/style.scss
Display user image at place of user name in Task Assignee column of Task table
=> feat(Task): display user avtar in task assignee column of task table

app/Models/Task.php, app/Queries/TaskDataTable.php
Added all option for task status in task filter drop down
=> feat(Task): added all option for task status in task filter drop down

resources/assets/js/task/task.js
fix bug delete time entry in task screen
=> feat(task): make delete timeentry function for task

resources/assets/js/task/task_detail.js, resources/views/tasks/show.blade.php
- ask for delete confirmation
- added comment edit icon
- added loader for save comment button
=> fix(comment): ask for delete confirm, added edit icon

resources/assets/style/sass/style.scss
below issue fixed in this PR
---
* #[165](https://track.infyom.com/tasks/TIMETRACKE-165) Data table data aligned vertically center
=> Harshad/ TIMETRACK-165 Data table data aliment vertically center 

app/Repositories/DashboardRepository.php, resources/assets/js/dashboard/dashboard.js, resources/assets/js/dashboard/developers-daily-report.js
#TIMETRACKE-156 Task should not be on custom toast which don't have 0 tracking time
=> Chart js tooltip "." issue

resources/assets/js/task/task_detail.js
Solve Task status is displayed differ in detail's edit popup
=> fix(task): task detail task status issue solve

resources/views/layouts/app.blade.php
Solve brand logo override iisue
=> feat(layout): TIMETRACK-160 brand logo override issue solve

resources/assets/js/task/task.js
=> fix(task): solve invalid date issue

resources/assets/js/custom.js
Make month name in shorten format
=> feat(Task): TIMETRACK-174 make month name in shorten format

resources/assets/style/sass/style.scss, resources/views/roles/edit_fields.blade.php, resources/views/roles/fields.blade.php
- Permissions label should be in bold
- remove space just before asterisk sign from Name 
- Role should be role in delete message popup
- Cancel button need consistency as in other page
=> fix(roles): #TIMETRACKE-178 UI and consistency in New/edit role screen

app/Http/Controllers/TimeEntryController.php, app/Repositories/TimeEntryRepository.php, resources/assets/js/task/task.js, resources/assets/js/time_entries/time_entry.js
* while some task is completed and we want to edit its entry manually into time-entry module, task not 
selected into dropdown.
=> Completed task should be selected while edit time entry

app/Models/Task.php, app/Repositories/TaskRepository.php, resources/assets/js/task/task.js, resources/views/tasks/table.blade.php
=> feat(task): Removed status from task

app/Http/Controllers/TaskController.php, app/Queries/TaskDataTable.php
Enhance task search by it's number
=> feat(task): added search by task number

resources/assets/js/custom.js
* Add/Edit Task popup should not close on outside click
=> fix(modal): Add/Edit Task popup should not close on outside click

resources/views/activity_types/index.blade.php, resources/views/layouts/app.blade.php, resources/views/layouts/menu.blade.php, resources/views/tasks/index.blade.php, resources/views/time_entries/index.blade.php, routes/web.php
`activityTypes` to `activity-types`
`timeEntries` to `time-entries`
=> (1) Routes name changed to dashed from camel-case

app/Repositories/DashboardRepository.php, app/helpers.php, resources/assets/js/dashboard/dashboard.js, resources/assets/js/dashboard/developers-daily-report.js
What change did?
- Fixed Work report and developer chart display the wrong time
- The chart does not render properly
- Make `This Month` default instead of `Last Week` in the work report
- Chart color generated random and remove fix colors 
- Remove extra code and improve query of devloper chart
=> Chart not rendering properly and wrong time display

app/Http/Controllers/TaskController.php, app/Http/Controllers/TimeEntryController.php, app/Models/Task.php, app/Models/TimeEntry.php, app/Queries/TaskDataTable.php, app/Repositories/DashboardRepository.php, app/Repositories/TaskRepository.php, app/Repositories/TimeEntryRepository.php, database/factories/ActivityTypeFactory.php, database/factories/TimeEntryFactory.php, database/migrations/2019_06_21_120121_migrate_value_of_task_number_in_tasks_table.php, tests/Integration/Models/TaskTest.php, tests/Integration/Models/TimeEntryTest.php
* scope `ofUser` added into TimeEntry module and its test added
* scope `ofProject` added into Task module and its test added
=> Task/TimeEntry Scope tests added 

.gitignore, app/Http/Controllers/ReportController.php, app/Repositories/ReportRepository.php, resources/views/reports/report_format.blade.php
What change did?
-  a percentage added into report. UI should look like
=> feat(reports): percentage support added into report

resources/assets/js/dashboard/dashboard.js
* remove next week option from the dashboard
=> fix(dashboard) : remove next week option from dashboard

resources/assets/js/time_entries/time_entry.js, resources/views/time_entries/edit_modal.blade.php, resources/views/time_entries/modal.blade.php
What change did?
* made start time and end time required into time entry
* Made duration filed always read-only
* put Place holder into start time and end time
=> fix(time-entry): make start time and end time required into time entry

resources/assets/js/report/report.js
https://gitlab.com/infy-apps/infy-tracker-issues/issues/20
=> #20 future date is not displaying while generate report

app/Models/ReportFilter.php, app/Repositories/ReportRepository.php, database/factories/ReportFactory.php, database/factories/ReportFilterFactory.php, resources/views/reports/report_format.blade.php, tests/Integration/Models/ReportFilterTest.php
New scopes : 
`ofParamType` to get data of `param_type` 
`ofReport` to get data of specific report id
=> Report filters scopes + tests added 

app/Http/Controllers/ReportController.php, app/Http/Controllers/TaskController.php, app/Models/Report.php, app/Queries/ReportDataTable.php, app/Repositories/TaskRepository.php, resources/assets/js/report/report.js, resources/assets/style/sass/report.scss, resources/views/layouts/app.blade.php, resources/views/reports/index.blade.php, resources/views/reports/table.blade.php
What change did?
* change list view to table view into a report screen
* created by added into the report table screen
* changed task creation flow due to created massive data
=> feat(report): change report list to report table and created by added

app/Models/Comment.php, resources/assets/js/task/task_detail.js, resources/views/tasks/show.blade.php
description found [here](https://gitlab.com/infy-apps/infy-tracker-issues/issues/16)
=> Task details screen changes

resources/assets/js/custom.js, resources/assets/js/projects/project.js, resources/assets/js/task/task.js, resources/assets/js/time_tracker/time_tracker.js
https://gitlab.com/infy-apps/infy-tracker-issues/issues/22
=> Revoke tracker popup on new task/projects create/update/delete

app/Http/Controllers/ReportController.php, app/Models/Report.php, app/Queries/ReportDataTable.php, app/Repositories/TaskRepository.php, resources/assets/js/report/report.js, resources/assets/style/sass/report.scss, resources/views/reports/create.blade.php, resources/views/reports/edit.blade.php, resources/views/reports/index.blade.php, resources/views/reports/report_format.blade.php, resources/views/reports/table.blade.php
https://gitlab.com/infy-apps/infy-tracker-issues/issues/43
=> Report screen fixes

app/Http/Controllers/TimeEntryController.php, app/Queries/TimeEntryDataTable.php, resources/assets/js/task/task.js, resources/assets/js/time_entries/time_entry.js, resources/views/layouts/app.blade.php, resources/views/layouts/menu.blade.php, resources/views/tasks/index.blade.php, resources/views/time_entries/index.blade.php, routes/web.php
* Logged in user should only allow seeing his time entry
* User can't delete others time entry if they don't have manage_entry permission
+
* In Task screen default render all tasks of logged in user
* Do not show add time entry button, if a user is not assigned to that task
=> Time Entry + Task Screen permissions fixes

app/Http/Controllers/TimeEntryController.php, app/Repositories/TimeEntryRepository.php
Solve duplicate time entry issue.
=> fix(time-entry): solve duplicate time entry issue

app/Http/Controllers/Auth/LoginController.php, app/Http/Controllers/Auth/RegisterController.php, app/Http/Controllers/Auth/ResetPasswordController.php, app/Http/Controllers/Auth/VerificationController.php, app/Http/Middleware/RedirectIfAuthenticated.php
Redirect user to dashboard page after login
=> fix(login): redirect user to dashboard page after login

app/Repositories/TimeEntryRepository.php
Fix time entry overlapping issue between duration
=> fix(timeEntry): fix time entry overlapping issue between duration

app/Http/Controllers/TimeEntryController.php, app/Queries/TimeEntryDataTable.php, resources/assets/js/time_entries/time_entry.js, resources/views/time_entries/index.blade.php
Added project filter in time entry screen
=> feat(time entry): added project filter in time entry screen

app/Repositories/TimeEntryRepository.php
solve time entry user overlapping issue
=> fix(time-entry): solve time entry user overlapping issue

resources/assets/style/sass/style.scss, resources/views/layouts/app.blade.php
* fixed issue https://gitlab.com/infy-apps/infy-tracker-issues/issues/50
=> Harshad/ #50 fixes footer issue of powered by text

resources/assets/js/time_entries/time_entry.js
=> fix(tacker): solve deprecation warning

app/Http/Controllers/TaskController.php, app/Queries/TaskDataTable.php, resources/assets/js/task/task.js, resources/views/tasks/index.blade.php
Added due date filter in task screen
=> feat(tasks): add due date filter in task screen

resources/views/tasks/show.blade.php
Solve task detail redirection issue
issue: https://gitlab.com/infy-apps/infy-tracker-issues/issues/67
=> fix(task-detail): solve back rediraction issue

resources/assets/js/time_entries/time_entry.js
time entry can not be made ahead of time
=> fix(time-entry): time entry can not be made ahead of time

resources/views/time_entries/edit_modal.blade.php, resources/views/time_entries/modal.blade.php
change design of time entry pop up
issue link: https://gitlab.com/infy-apps/infy-tracker-issues/issues/64
=> feat(time-entry): change design of time entry pop up

app/Repositories/TaskRepository.php, resources/assets/js/task/task.js, resources/views/tasks/task_details.blade.php
added datatable for time entries table in task detail pop up
issue link: https://gitlab.com/infy-apps/infy-tracker-issues/issues/72
=> feat(task-detail): added datatable for time entry table

app/Repositories/ReportRepository.php
solve edit report client filter
=> fix(report): solve edit report client filter

resources/assets/js/profile/profile.js, resources/assets/style/sass/style.scss, resources/views/profile/edit_profile.blade.php
fix: 
- resize upload image button size in edit profile pop up
Enhancement:
- added password view functionality for password fields in edit profile pop up
issue link: https://gitlab.com/infy-apps/infy-tracker-issues/issues/86
=> fix(edit-profile): added password view/block functionality

resources/assets/js/dashboard/dashboard.js, resources/assets/js/dashboard/developers-daily-report.js, resources/assets/js/time_entries/time_entry.js, resources/views/dashboard/index.blade.php
Enhancement: dashboard
-  remove unused projects from custom report
issue link: https://gitlab.com/infy-apps/infy-tracker-issues/issues/74
=> feat(dashboard): remove unused projects from custom report in dashboard

app/Repositories/DashboardRepository.php, tests/Repositories/DashboardRepositoryTest.php
Enhancement: dashboard
- change date format in dashboard custom report chart's x-axis
(Review)
=> feat(dashboard): chnage date formate

resources/assets/js/task/task.js
Fix: tasks screen
- in task detail pop up Task Time Entries is not collapsing on task screen
issue link: https://gitlab.com/infy-apps/infy-tracker-issues/issues/87
=> fix(task-detail): try to fix task-detail pop up collaps row issue

app/Repositories/ReportRepository.php, resources/views/reports/report_format.blade.php
Enhancement: report view screen
- added task detail link in tasks in report view screen
=> feat(report): added task link in report view screen

resources/assets/js/task/task.js, resources/assets/js/task/task_detail.js, resources/views/clients/edit_modal.blade.php, resources/views/clients/modal.blade.php, resources/views/tags/edit_modal.blade.php, resources/views/tags/modal.blade.php, resources/views/tasks/edit_modal.blade.php, resources/views/tasks/modal.blade.php, resources/views/time_entries/modal.blade.php, resources/views/users/edit_modal.blade.php, resources/views/users/modal.blade.php
Bug fix: console warning
- solve console warning in client, users, tasks, time entries and tags screen
issue link: https://gitlab.com/infy-apps/infy-tracker-issues/issues/89
=> fix(UI): solve console warning

resources/assets/js/task/task_detail.js
Bug Fixes:
- On Task detail-screen , In Edit task, while adding a description field, and by saving it error throw as shown in image
- There is no Assignee into assign field in Edit Task popup but there is assignee on task detail screen.
(Ref)
issue link: https://gitlab.com/infy-apps/infy-tracker-issues/issues/91
=> fix(task-detail): solve edit task error in task detail page

resources/views/roles/edit_fields.blade.php, resources/views/roles/fields.blade.php
Bug fix: solve UI issue of check box in roles create and edit screen
- Adjust check box text in a single row instead of double.
- Checkbox was not responsive, fixed that issue.
issue link: https://gitlab.com/infy-apps/infy-tracker-issues/issues/88
=> fix(roles): improve role add edit ui

app/Models/User.php, resources/views/dashboard/index.blade.php
Enhancement: User profile image
- If user does not have uploaded his/her profile picture yet than instead of showing dummy user image we are showing image icon with his name letters, Eg. if user name is John Doe than image with "JD" will be displayed.
Ref:
- Reduce width of users dropdown in dashboard custom report chart
=> feat(user-profile): changed user-avtar image to user name image

app/Queries/TimeEntryDataTable.php
Bug Fix: time entry screen
If admin user filter by project than no time entry was coming, now it is fix.
=> fix(time-entry): solve time entry project filter for admin

resources/assets/js/profile/profile.js, resources/assets/style/sass/style.scss, resources/views/profile/edit_profile.blade.php
enhancement: profile edit
- added Hand cursor on the Eye icon
- Icon must be changed if the user clicks on the Eye icon to show their password
issue link: https://gitlab.com/infy-apps/infy-tracker-issues/issues/103
=> feat(profile): Hidden icon for passwords on profile screen

resources/assets/style/sass/style.scss
enhancement: pop up
- Make Alignment proper between module name & close button.
Reference:
issue link: https://gitlab.com/infy-apps/infy-tracker-issues/issues/99
=> fix(modal): fix allignment issue in modal

resources/assets/js/custom.js, resources/assets/js/time_entries/time_entry.js, resources/views/tasks/edit_modal.blade.php, resources/views/tasks/modal.blade.php, resources/views/time_entries/edit_modal.blade.php, resources/views/time_entries/modal.blade.php
fix: UI
- added first focus in modal for input or textarea fields only
issue link: https://gitlab.com/infy-apps/infy-tracker-issues/issues/110
=> fix(UI): added first focus for input fields only

app/Repositories/TaskRepository.php
Fix: added project relation in task detail query
=> fix(task_detail): added project relation in task detail

app/Http/Controllers/TaskController.php, app/Repositories/TaskRepository.php, composer.json
**Bug Fixes:**
* FIX: Search should be worked on task and time entry
* FIX: fix console error in time entry
=> Release v1.8.5-alpha

app/Http/Controllers/TimeEntryController.php, app/Repositories/TimeEntryRepository.php, tests/Repositories/TimeEntryRepositoryTest.php
Enhancement: Time-entry task
- admin can see all task and can do time entry in any task, so if admin try to do entry in task which is not assigned to him/her than at that time task automatically assigned to user.
=> feat(time-entry): Task assign automatically if time track by admin and task not assigned

resources/assets/js/report/report.js
Bug Fixes: Reports
- before start date and end was display same in reports table, now fixed that issue
Issue link: https://gitlab.com/infy-apps/infy-tracker-issues/issues/122
=> feat(reports): solve start/end date issue

resources/assets/js/users/user.js
Bug Fixes: Users Table
- Remove sorting at Action column and add to salary column
- manage with of columns
Issue link: https://gitlab.com/infy-apps/infy-tracker-issues/issues/130
=> feat(users): solve column width and orderable issue

resources/views/tasks/show.blade.php
Bug Fix: Task detail screen
solve header alignment issue
issue link: https://gitlab.com/infy-apps/infy-tracker-issues/issues/120
=> fix(task-detail): solve header alignment issue

app/Models/User.php, app/Repositories/ReportRepository.php, composer.json, resources/assets/js/report/report.js, resources/assets/js/users/user.js, resources/assets/style/sass/style.scss, resources/views/reports/report_format.blade.php, resources/views/tasks/show.blade.php
FIX: Header alignment UI issue fix [120](https://gitlab.com/infy-apps/infy-tracker-issues/issues/120)
FIX: Show user image instead of dummy image if user has uploaded image [417](https://github.com/InfyOmLabs/infy-tracker/pull/417)
FIX: Cost report fixes
FIX: before start date and end was display same in reports table, now fixed that issue
FIX: solve column width and orderable issue [130](https://gitlab.com/infy-apps/infy-tracker-issues/issues/130)
=> V0.1.3-beta Release 

app/Http/Controllers/UserController.php, app/Http/Requests/ChangePasswordRequest.php, app/Repositories/UserRepository.php, resources/assets/js/profile/profile.js, resources/views/layouts/app.blade.php, resources/views/profile/change_password.blade.php, resources/views/profile/edit_profile.blade.php, routes/web.php
password & cpassword removed from profile section and new modal for change password is created.
=> change password added

app/Http/Controllers/UserController.php, app/Http/Requests/ChangePasswordRequest.php, app/Models/User.php, app/Repositories/DashboardRepository.php, app/Repositories/UserRepository.php, composer.json, composer.lock, resources/assets/js/profile/profile.js, resources/views/layouts/app.blade.php, resources/views/profile/change_password.blade.php, resources/views/profile/edit_profile.blade.php, routes/web.php
**Enhancement**
* Change Password model added
* Inactive user should not display in Dashboard
=> Release v0.1.5-beta

app/Events/AddComment.php, app/Events/DeleteComment.php, app/Events/StartTimer.php, app/Events/StopWatchStop.php, app/Events/UpdateComment.php, app/Http/Controllers/Controller.php, app/Models/User.php, composer.json, config/app.php, config/ide-helper.php, resources/views/layouts/app.blade.php, resources/views/tasks/time_tracking_modal.blade.php, tests/Controllers/ActivityTypeControllerTest.php, tests/Controllers/ClientControllerTest.php, tests/Controllers/CommentControllerTest.php, tests/Controllers/HomeControllerTest.php, tests/Controllers/ProjectControllerTest.php, tests/Controllers/TagControllerTest.php, tests/Controllers/TaskControllerTest.php, tests/Controllers/TimeEntryControllerTest.php, tests/Controllers/UserControllerTest.php, tests/Controllers/Validations/UserControllerValidationTest.php
* Fix image hight issue in the time entry model opening in the task detail screen
* Change footer copyright Year
=> Release 0.1.6-beta

resources/views/tasks/show.blade.php, resources/views/tasks/time_tracking_modal.blade.php
- Start Time column added into time entry model opening from the task detail screen 
- End Time column added into time entry model opening from the task detail screen
=> Start and End Time column added in Time Entry Model opening from task detail screen

app/Http/Controllers/HomeController.php, app/Http/Controllers/ProjectController.php, app/Http/Controllers/ReportController.php, app/Http/Controllers/TaskController.php, app/Http/Controllers/TimeEntryController.php, app/Queries/ProjectDataTable.php, app/Queries/TaskDataTable.php, app/Queries/TimeEntryDataTable.php, app/Repositories/AccountRepository.php, app/Repositories/UserRepository.php, composer.json, database/migrations/2019_09_14_060733_create_permission_tables.php, package-lock.json, resources/views/tasks/show.blade.php, resources/views/tasks/time_tracking_modal.blade.php, routes/web.php, tests/Controllers/ProjectControllerTest.php, tests/Controllers/Validations/TimeEntryControllerValidationTest.php, tests/Controllers/Validations/UserControllerValidationTest.php, tests/DuskTestCase.php, tests/Permissions/ProjectControllerPermissionTest.php
- Start Time and End Time column added into the Time Entry model opening from the task detail page
=> Release v0.1.7-beta

app/Http/Controllers/ClientController.php, app/Queries/ClientDataTable.php, resources/assets/js/clients/client.js, resources/views/clients/index.blade.php
What changes?
**Fixes:**
* if department is not set in client than show empty value in client column in clients page
=> feat(client): if department is not set in client than show empty value

app/Http/Controllers/ClientController.php, app/Queries/ClientDataTable.php, resources/assets/js/clients/client.js, resources/views/clients/index.blade.php
**Enhancement**
- Department filter add into clients table
**FIX**
- fix the sorting issue in the client on the department column
=> Release v0.1.6-beta

resources/assets/js/time_tracker/time_tracker.js
changes- 
- task notes are stored in local storage
- set notes after page refresh from local storage
=> feat(time-entry): task notes are stored into local storage

resources/assets/js/report/report.js, resources/views/reports/fields.blade.php
Changes-
- placeholder added to client field in reports form so that first Client will not get selected
=> fix(report): first Client got selected in report issue fixes

resources/views/reports/index.blade.php
changes - 
- set logged in user as a default value in created by filter in reports
=> refactor(report): Logged in user default selected into created by filter into reports

app/Repositories/TaskRepository.php
changes :-
- assign the task by default to the user who create the same / along with the user who assign the tasks to other users
=> refactor(task): assign the task by default who created the same

app/Http/Controllers/ReportController.php
changes :-
- redirect on view report page while Report create or edit
=> refactor(report): redirect on view report page while Report create or edit

.travis.yml, resources/assets/style/sass/style.scss, resources/views/auth/login.blade.php
changes :-
- solve login screen css layout issue for login form that is not properly displaying.
=> fix(login): solve login screen css layout issue for login form

app/Http/Controllers/ReportController.php, app/Repositories/UserRepository.php
change :-
- show only email verified users in dropdown in tasks and report module
- also test in other modules whether the same is working in their dropdowns
=> refactor: show only email verified users in dropdown in tasks and report module

app/Http/Controllers/TimeEntryController.php, app/Repositories/TimeEntryRepository.php
- only auth user's activity will be copied
- change created_at to start date in condition otherwise if user will create yesterday's entry then it will also copied
- if user add entry in same task again then only last entry's data was being copied that's why i changed taskId to id in TimeEntryController
=> fix(time-entry): Only own activity should be copied in copy to clipboard function

resources/assets/js/time_entries/time_entry.js, resources/views/time_entries/table.blade.php
- add project name into time-entry data-table
=> refactor(time-entry): Add Project Column into time entry table

resources/assets/js/task/task.js, resources/views/tasks/index.blade.php
- Remove Default current date from Due Date filter in Task Screen
=> refactor(tasks): Default current date Removed from Due Date filter in Task Screen

resources/assets/js/task/task.js
change :-
- due date should be red in color if the same is over
=> refactor(task): due date should be red in color if the same is over

resources/assets/js/task/task.js, resources/views/tasks/table.blade.php
change :-
- show priority for respective task on tasks listing screen
=> refactor(task): show priority for respective task on tasks listing screen

app/Repositories/ProjectRepository.php, app/Repositories/TaskRepository.php, resources/views/layouts/menu.blade.php, resources/views/tasks/index.blade.php, routes/web.php
change :-
- show users and projects dropdown list if they have manage tasks permission
=> feat(task): All user list and projects only display who have manage task permission

resources/assets/js/task/task.js, resources/views/tasks/index.blade.php
change :-
- do logged in user name selected in assignee dropdown under New Task modal
=> Logged in user auto  selected in assignee dropdown in new  task model

app/Repositories/DashboardRepository.php, resources/assets/js/dashboard/dashboard.js, resources/assets/js/task/task.js
What changes?
Enhancement:
- Display Total Hours in custom report in tooltip
=> TRAKER-379: Display Total Hours in custom report in tooltip

app/Http/Controllers/TimeEntryController.php, app/Queries/TimeEntryDataTable.php, resources/assets/js/time_entries/time_entry.js, resources/views/time_entries/index.blade.php
Changes :
Enhancement
* Filter the time entries list based on the date selected.
=> TRAKER-362 Add Date filter into Time Entry

app/Queries/UserDataTable.php
What changes?
Enhancement:
- Active users will come first in user listing
=> TRACKER-381: Active users will come first in user listing

app/Http/Controllers/ProjectController.php, app/Models/TimeEntry.php, app/Repositories/ProjectRepository.php, app/Repositories/TaskRepository.php, app/Repositories/TimeEntryRepository.php, resources/assets/js/time_entries/time_entry.js, resources/assets/js/time_tracker/time_tracker.js, resources/views/time_entries/edit_modal.blade.php, resources/views/time_entries/modal.blade.php, routes/web.php, tests/Controllers/Validations/TimeEntryControllerValidationTest.php
What changes?
Enhancement:
- Admin can add/update user's time entry from time-entry and task's screen
=> Tracker-383: Admin can add/update any user's timeentry

app/Http/Controllers/TaskController.php, package.json, resources/assets/js/task/task.js, resources/assets/js/task/task_detail.js, resources/assets/style/sass/style.scss, resources/views/tasks/edit_modal.blade.php, resources/views/tasks/index.blade.php, resources/views/tasks/modal.blade.php, resources/views/tasks/show.blade.php, webpack.mix.js
Change :
Enhancement
- Implement the Quill Editor in place of CKEditor
=> TRAKER-365 Replace ckeditor with Quill editor

app/Repositories/TaskRepository.php, resources/assets/js/task/task_detail.js
changes :
Fix :
*  solve the .jpeg/.jpg image not uploading for attachments while taking snap shoot from snipping tool under Task Detail screen
* also fix the same issue for .png images while saving the image using snipping tool
=> #TRAKER-364 JPEG should be support into attachments in task detail screen

app/Repositories/ProjectRepository.php, app/Repositories/TimeEntryRepository.php, resources/views/time_entries/index.blade.php
What changes?
Enhancement:
- for project filter in time-entry screen render all project if user has manage_time_entry permission otherwise only assigned projects will come in that filter
=> feat(time entry): for time-entry filter get projects having permission

resources/views/tasks/index.blade.php
=> fix(tasks): console error of daterangepicker on task screen fixes
